name: Docker CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test-container:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        # This runs the exact same build command you ran on your laptop!
        run: docker build -t my-python-app .

      - name: Run Tests Inside Container
        # We run the container, but override the default command to run 'pytest' 
        # instead of running the normal app.py
        run: docker run my-python-app pytest