name: Python Unit Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        # This reads the requirements.txt file and installs pytest
        run: pip install -r requirements.txt

      - name: Run Pytest
        # This executes our test file automatically
        run: pytest